### ISSUE TITLE
FYI: Container actions only work on linux builds

### ISSUE THREAD

**Issue by rjstone** [Ilshidur/action-discord#11]
Doesn't work for windows builds. Might want to mention in docs.

**Comment by Rkbhasan1** [comment]
what is work for my builds ?this is my personal  subject .plese don't distrib me.-:)

**Comment by Rkbhasan1** [comment]
yes.

IBM.Com

**Comment by Ilshidur** [comment]
Hello. Sorry for the late response. I finally have some free time to check this issue. Thanks for your patience.

**Comment by rosman21** [comment]
Confirming this is still an issue I am getting the error on the following builds.
```
Run Ilshidur/action-discord@cc38eb40798e4aafd43ae51e8dd3e507dc57234e
##[error]Container action is only supported on Linux
```

**Comment by Ilshidur** [comment]
Hello. Sorry, I totally forgot about this issue.

Apparently, containerized Actions can only runs on Linux environments according to this doc : https://help.github.com/en/actions/building-actions/about-actions#types-of-actions

I can't find any proper way to make it compatible, except to migrate it to a pure Javascript Action, which would make it a breaking change.

For now, if you use a GitHub-hosted runner, I recommend to use the `ubuntu-18.04` environment :

```yaml
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
```

Sorry to answer this issue after so long ... only to provide so little help.

If someone has a workaround for this, I would be glad to document this or apply a fix. I admit that this can be a pain. Let's hope that GitHub has planned some solutions in the near future 🤞 .
