### ISSUE TITLE
didn't show link in discord msg

### ISSUE THREAD

**Issue by bluelovers** [Ilshidur/action-discord#18]
in doc desc can see this pic , it has link attach

![image](https://user-images.githubusercontent.com/167966/73095074-ced63380-3f1c-11ea-8a86-d4ffb7102b33.png)

but in my test , it only has text msg

![image](https://user-images.githubusercontent.com/167966/73095060-c8e05280-3f1c-11ea-8c81-5b1855ebf3fb.png)

**Comment by Ilshidur** [comment]
Hello. Here is the content of the workflow that was used for the picture :

```yaml
name: Notification on push

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: OSS 117
        DISCORD_AVATAR: https://resize.programme-television.ladmedia.fr/r/670,670/img/var/premiere/storage/images/tele-7-jours/news-tv/oss-117-le-caire-nid-d-espions-c8-le-show-de-jean-dujardin-4484285/90175763-1-fre-FR/OSS-117-Le-Caire-nid-d-espions-C8-Le-show-de-Jean-Dujardin.jpg
      uses: Ilshidur/action-discord@master
      with:
        args: 'A new commit has been pushed to Ilshidur/action-discord.'
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
```

I think you should remove this eventual part in your workflow :

```yaml
with:
    args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
```

This will prevent the (automatically) formatted message to be overridden by "The project ... deployed".
