### ISSUE TITLE
Error : 400 Bad Request

### ISSUE THREAD

**Issue by bluelovers** [Ilshidur/action-discord#40]
action trigger by schedule task

```yml
on:
  push:
    branches:
      - master
  schedule:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#scheduled-events-schedule
#            ┌───────────── minute (0 - 59)
#            │ ┌───────────── hour (0 - 23)
#            │ │ ┌───────────── day of the month (1 - 31)
#            │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
#            │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
#            │ │ │ │ │
#            │ │ │ │ │
#            │ │ │ │ │
#            * * * * *
    - cron: '0 0 * * 1'
    - cron: '0 0 * * 5'
```

![image](https://user-images.githubusercontent.com/167966/89598381-3c312c80-d88f-11ea-9283-9c49cc6fc21b.png)

```
Sending message ...
Error : 400 Bad Request
Message : { sender: [ 'This field is required' ] }
```

**Comment by Ilshidur** [comment]
Hello. Apparently, a field is missing and the Discord API refuses the process the request. Could you provide more informations about the environment variables you pass to this Action, please ?

Also, do you prepend `/github` to the Discord webhook ?

**Comment by bluelovers** [comment]
```yml
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
```

---

> Also, do you prepend /github to the Discord webhook ?

nope
