### ISSUE TITLE
Use GitHub environment variables in the Discord message

### ISSUE THREAD

**Issue by Sv443** [Ilshidur/action-discord#6]
Hi!
I was trying to add the commit SHA to the Discord message using the `env.GITHUB_SHA` [GitHub environment variable](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables). But no matter how I tried to do this, it never worked out.  
I want to achieve a message like this:  
```
CI run was successful.
https://github.com/Sv443/Project/[COMMIT_SHA_HERE]/actions
```
I've never really used bash, nor did I ever use this GitHub action, so please tell me how I could achieve this or whether you could add this feature.

**Comment by Ilshidur** [comment]
Hello. This is a missing feature. I'll start to work on it ASAP and you'll get an update when I release it. You can expect it in < 2 days.

**Comment by Sv443** [comment]
> 
> 
> Hello. This is a missing feature. I'll start to work on it ASAP and you'll get an update when I release it. You can expect it in < 2 days.

Nice, thanks!

**Comment by Sv443** [comment]
whoops sorry

**Comment by Ilshidur** [comment]
I pushed a release. You can now interpolate environment variables in your arguments.
More details here : https://github.com/Ilshidur/action-discord#arguments

I'd be glad to hear some feedback from you ;-)

**Comment by Sv443** [comment]
I've implemented the `GITHUB_SHA` variable to directly link to the action log:
```yml
    - name: Discord success notification # sends a Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '☑️ JokeAPI CI run was successful (https://github.com/Sv443/JokeAPI/commit/{{GITHUB_SHA}}/checks)' 
    - name: Discord failure notification # sends a Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '🚫 JokeAPI CI run failed (https://github.com/Sv443/JokeAPI/commit/{{GITHUB_SHA}}/checks)'
      if: failure()
```
and it works perfectly! Thanks! 😄  
![grafik](https://user-images.githubusercontent.com/38158426/69009198-6fbfd580-0953-11ea-84e6-0fd54a403c90.png)
