### ISSUE TITLE
"Env var DISCORD_WEBHOOK not defined" when run on push

### ISSUE THREAD

**Issue by Sv443** [Ilshidur/action-discord#71]
I've been getting this error since like a week or so now. It only happens when the workflow is triggered automatically by the push event:  
  
![grafik](https://user-images.githubusercontent.com/38158426/117142441-01254080-adb0-11eb-825b-6f53de9f25e1.png)  
  
But as soon as I re-run the job, it works fine:  
  
![grafik](https://user-images.githubusercontent.com/38158426/117142515-14d0a700-adb0-11eb-94c4-0f1932b1c645.png)  
  
Idk if I'm just doing something wrong or if there's a bug so that's why I'm opening an issue.  
I've double checked the `DISCORD_WEBHOOK` secret exists and is correct.  
  
Here's the relevant part of the workflow YAML file (full file [here](https://github.com/Sv443/JokeAPI/blob/master/.github/workflows/nodejs.yml)):  
```yml
    - name: Discord success notification # sends a Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '✅ **JokeAPI CI** (triggered by `{{GITHUB_ACTOR}}` on `{{GITHUB_REF}}`) was successful (see https://github.com/Sv443/JokeAPI/commit/{{GITHUB_SHA}}/checks)' 
    - name: Discord failure notification # sends a Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '🚫 **JokeAPI CI** (triggered by `{{GITHUB_ACTOR}}` on `{{GITHUB_REF}}`) has failed (see https://github.com/Sv443/JokeAPI/commit/{{GITHUB_SHA}}/checks)'
      if: failure()
```
