### ISSUE TITLE
Default message not working?

### ISSUE THREAD

**Issue by JoaoCnh** [Ilshidur/action-discord#81]
I've tried running the action with no args to replicate the embed example in the README but no messages is being sent.
What is required to send that message?

**Comment by chrissound** [comment]
Yup having just:

```
      - name: Actions for Discord
        uses: Ilshidur/action-discord@0.3.2
        if: always()
        env:
          DISCORD_WEBHOOK: ***
```

Does not make it run anything for me, the step is not even shown in github actions.
